local library = loadstring(game:HttpGet("https://pastebin.com/raw/eWKgbdix", true))()
local window = library:CreateWindow('Weapon Masters V0.1')
window:Section('Auto Farm')
local tab = window:Toggle('Swing', {flag = "toggle1"})
local tab = window:Toggle('Rebirth', {flag = "toggle1"})
local tab = window:Toggle('Prestige', {flag = "toggle1"})
window:Section('Coming Soon')
local b = w:Button("Example Button", function()
   print(w.flags.toggle1)
end)
